# Generated by Django 4.0.4 on 2022-04-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='img/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modifield', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='news', to='news.category')),
            ],
        ),
    ]
